GH #12 - Added Contribution Guidelines in CONTRIBUTING.md
indeedeng/util pull request #27
Opened 2020-10-07 02:44 UTC by hnarasaki

GH #12 - Added Contribution Guidelines in CONTRIBUTING.md

2020-10-08 21:24 UTC, DuaneOBrien requested changes

2020-10-08 21:24 UTC, DuaneOBrien commented on CONTRIBUTING.md
> +In order for your change to be accepted, the [TravisCI](https://travis-ci.com/indeedeng/cluster-preset) pipeline must complete successfully.
Looking through the existing repo it doesn't look like there are many unit tests for the other parts of the code, and I don't think adding test here will kick off the travis pipeline. We could probably keep the unit tests requirement but drop the travis pipeline sentence.

2020-10-08 21:24 UTC, DuaneOBrien commented on CONTRIBUTING.md
> +ClusterPreset is governed by the [Contributor Covenant v1.4.1](CODE_OF_CONDUCT.md).
Could just changes this to say "This project" rather than ClusterPreset

2020-10-08 21:24 UTC, DuaneOBrien commented on CONTRIBUTING.md
> +2. Assign the ticket to yourself, and/or leave a comment on the issue that you would like to work on it.
The contributor should wait for confirmation from the project before starting work, as this one isn't rigorously maintained.

2024-05-17 21:15 UTC, mmorrisontx commented
Closing all pulls, as this repository is now archived.

2024-05-17 21:15 UTC, closed without merging